import { Hotel, Restaurant, Activity } from '../types/recommendations';

// Common images
const COMMON_IMAGES = {
  hotel: 'https://images.unsplash.com/photo-1566073771259-6a8509689945?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
  restaurant: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80',
  activity: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80'
};

export const hotels: Hotel[] = [
  {
    id: 'hotel1',
    name: 'Taj Coromandel',
    city: 'Chennai',
    city_id: 'chennai',
    price_per_night: 12000,
    rating: 4.8,
    type: 'luxury',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Pool', 'Spa', 'Restaurant', 'Gym'],
    location: 'Nungambakkam',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel2',
    name: 'Novotel Chennai',
    city: 'Chennai',
    city_id: 'chennai',
    price_per_night: 8000,
    rating: 4.5,
    type: 'luxury',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Pool', 'Spa', 'Restaurant', 'Gym'],
    location: 'OMR',
    src: 'https://images.unsplash.com/photo-1520250497591-112f0f6c1c8a?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel3',
    name: 'The Residency',
    city: 'Chennai',
    city_id: 'chennai',
    price_per_night: 6000,
    rating: 4.3,
    type: 'mid-range',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Restaurant', 'Gym', 'WiFi'],
    location: 'T Nagar',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel4',
    name: 'ITC Grand Chola',
    city: 'Chennai',
    city_id: 'chennai',
    price_per_night: 15000,
    rating: 5.0,
    type: 'luxury',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Pool', 'Spa', 'Restaurant', 'Gym', 'Conference'],
    location: 'Mount Road',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel5',
    name: 'Hotel Savera',
    city: 'Chennai',
    city_id: 'chennai',
    price_per_night: 4000,
    rating: 4.2,
    type: 'budget',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Restaurant', 'WiFi'],
    location: 'City Center',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel6',
    name: 'GRT Regency',
    city: 'Coimbatore',
    city_id: 'city3',
    price_per_night: 5500,
    rating: 4.3,
    type: 'mid-range',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Pool', 'Restaurant', 'Gym', 'WiFi'],
    location: 'Race Course',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel7',
    name: 'The Residency Towers',
    city: 'Coimbatore',
    city_id: 'city3',
    price_per_night: 4500,
    rating: 4.1,
    type: 'mid-range',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Restaurant', 'Gym', 'WiFi'],
    location: 'RS Puram',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel8',
    name: 'The Gateway Hotel',
    city: 'Coimbatore',
    city_id: 'city3',
    price_per_night: 7000,
    rating: 4.6,
    type: 'luxury',
    suitable_for: ['solo', 'family', 'couple'],
    amenities: ['Pool', 'Spa', 'Restaurant', 'Gym', 'WiFi'],
    location: 'Avinashi Road',
    src: 'https://images.unsplash.com/photo-1566073771259-6a8509689948?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel9',
    name: 'The Madurai Residency',
    city: 'Madurai',
    city_id: 'madurai',
    price_per_night: 2800,
    rating: 4.4,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'restaurant', 'gym', 'wifi'],
    location: 'KK Nagar',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel10',
    name: 'Fortune Pandiyan',
    city: 'Madurai',
    city_id: 'madurai',
    price_per_night: 3500,
    rating: 4.6,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'spa', 'restaurant', 'gym', 'wifi', 'conference'],
    location: 'Race Course',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel11',
    name: 'GRT Regency',
    city: 'Madurai',
    city_id: 'madurai',
    price_per_night: 3000,
    rating: 4.5,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'restaurant', 'gym', 'wifi'],
    location: 'Alagarkoil Road',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel12',
    name: 'The Gateway Hotel',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 3800,
    rating: 4.5,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'spa', 'restaurant', 'gym', 'wifi', 'conference'],
    location: 'Peelamedu',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel13',
    name: 'Radisson Blu',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 4200,
    rating: 4.7,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'spa', 'restaurant', 'gym', 'wifi', 'conference'],
    location: 'Singanallur',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel14',
    name: 'The Residency Towers',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 3200,
    rating: 4.4,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'restaurant', 'gym', 'wifi'],
    location: 'DB Road',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel15',
    name: 'Vivanta by Taj',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 4500,
    rating: 4.8,
    type: 'luxury',
    suitable_for: ['family', 'couple', 'business'],
    amenities: ['pool', 'spa', 'restaurant', 'gym', 'wifi', 'conference'],
    location: 'Race Course',
    src: '',
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel16',
    name: 'Hotel Grand Palace',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 2500,
    rating: 4.2,
    type: 'budget',
    suitable_for: ['family', 'solo', 'business'],
    amenities: ['wifi', 'restaurant', 'ac', 'parking'],
    location: 'Gandhipuram',
    src: COMMON_IMAGES.hotel,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel17',
    name: 'Hotel SPR Inn',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 2800,
    rating: 4.3,
    type: 'budget',
    suitable_for: ['family', 'solo', 'business'],
    amenities: ['wifi', 'restaurant', 'ac', 'parking'],
    location: 'City Center',
    src: COMMON_IMAGES.hotel,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel18',
    name: 'Hotel Le Grand',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 3000,
    rating: 4.4,
    type: 'budget',
    suitable_for: ['family', 'solo', 'business'],
    amenities: ['wifi', 'restaurant', 'ac', 'parking'],
    location: 'RS Puram',
    src: COMMON_IMAGES.hotel,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel19',
    name: 'Hotel Apple Park',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 3200,
    rating: 4.5,
    type: 'budget',
    suitable_for: ['family', 'solo', 'business'],
    amenities: ['wifi', 'restaurant', 'ac', 'parking'],
    location: 'Race Course',
    src: COMMON_IMAGES.hotel,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel20',
    name: 'Hotel Vishnu Priya',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    price_per_night: 2700,
    rating: 4.3,
    type: 'budget',
    suitable_for: ['family', 'solo', 'business'],
    amenities: ['wifi', 'restaurant', 'ac', 'parking'],
    location: 'Gandhipuram',
    src: COMMON_IMAGES.hotel,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'hotel6',
    name: 'Hotel Grand Palace',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.2,
    location: 'Near Meenakshi Temple',
    description: 'Luxury hotel with modern amenities',
    price_per_night: 2800,
    amenities: ['WiFi', 'AC', 'Pool', 'Restaurant'],
    src: COMMON_IMAGES.hotel,
    type: 'luxury',
    suitable_for: ['family', 'solo', 'business'],
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  }
];

export const restaurants: Restaurant[] = [
  {
    id: 'rest1',
    name: 'Peshawri',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.7,
    cuisine: 'North Indian',
    suitable_for: ['solo', 'family', 'couple'],
    location: 'ITC Grand Chola',
    src: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80',
    description: 'Authentic North Indian cuisine',
    specialties: ['Dal Bukhara', 'Tandoori Chicken'],
    timings: '12:00 PM - 11:00 PM',
    nearby_hotels: ['hotel1'],
    avg_cost_per_person: 2500,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res2',
    name: 'Murugan Idli Shop',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.7,
    cuisine: 'South Indian',
    suitable_for: ['family', 'friends'],
    location: 'T Nagar',
    src: '/images/murugan_idly.jpeg',
    description: 'Renowned for soft idlis and flavorful chutneys',
    specialties: ['Idli', 'Pongal', 'Vada'],
    timings: '6:00 AM - 10:00 PM',
    nearby_hotels: ['hotel1', 'hotel3'],
    avg_cost_per_person: 200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res3',
    name: 'Junior Kuppanna',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.6,
    cuisine: 'Chettinad',
    suitable_for: ['family', 'friends'],
    location: 'Egmore',
    src: '/images/junior.jpg',
    description: 'Famous for Chettinad cuisine',
    specialties: ['Chicken Chettinad', 'Mutton Sukka'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel2', 'hotel4'],
    avg_cost_per_person: 400,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res4',
    name: 'Thalappakatti',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.5,
    cuisine: 'Non-Vegetarian',
    suitable_for: ['family', 'friends'],
    location: 'Nungambakkam',
    src: '/images/thalapakati.jpg',
    description: 'Known for authentic Dindigul biryani',
    specialties: ['Mutton Biryani', 'Chicken Biryani'],
    timings: '11:30 AM - 11:00 PM',
    nearby_hotels: ['hotel3', 'hotel5'],
    avg_cost_per_person: 350,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res5',
    name: 'Anjappar',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.4,
    cuisine: 'Chettinad',
    suitable_for: ['family', 'friends'],
    location: 'Nungambakkam',
    src: '/images/anjappar.jpg',
    description: 'Specializes in Chettinad cuisine',
    specialties: ['Chicken 65', 'Mutton Chukka'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel4', 'hotel5'],
    avg_cost_per_person: 450,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res6',
    name: 'Annapoorna',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.4,
    cuisine: 'south_indian',
    suitable_for: ['family', 'friends'],
    location: 'RS Puram',
    src: '',
    description: 'Famous for authentic South Indian breakfast',
    specialties: ['Idli', 'Dosa', 'Pongal'],
    timings: '6:00 AM - 10:00 PM',
    nearby_hotels: ['hotel2', 'hotel3', 'hotel4'],
    avg_cost_per_person: 200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res7',
    name: 'Sree Krishna Sweets',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.5,
    cuisine: 'south_indian',
    suitable_for: ['family', 'friends'],
    location: 'RS Puram',
    src: '',
    description: 'Popular for traditional sweets and snacks',
    specialties: ['Mysore Pak', 'Laddu', 'Murukku'],
    timings: '8:00 AM - 10:00 PM',
    nearby_hotels: ['hotel2', 'hotel3'],
    avg_cost_per_person: 150,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res8',
    name: 'Junior Kuppanna',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.3,
    cuisine: 'north_indian',
    suitable_for: ['family', 'friends'],
    location: 'Race Course',
    src: '',
    description: 'Known for North Indian cuisine',
    specialties: ['Butter Chicken', 'Naan', 'Biryani'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel3', 'hotel4'],
    avg_cost_per_person: 400,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res9',
    name: 'The French Door',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.6,
    cuisine: 'continental',
    suitable_for: ['couple', 'friends'],
    location: 'RS Puram',
    src: '',
    description: 'Fine dining with French cuisine',
    specialties: ['Escargot', 'Duck Confit', 'Crème Brûlée'],
    timings: '12:00 PM - 11:00 PM',
    nearby_hotels: ['hotel2', 'hotel5'],
    avg_cost_per_person: 1200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res10',
    name: 'Noodle Bar',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.4,
    cuisine: 'chinese',
    suitable_for: ['family', 'friends'],
    location: 'Peelamedu',
    src: '',
    description: 'Authentic Chinese cuisine',
    specialties: ['Dim Sum', 'Noodles', 'Hot Pot'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel4', 'hotel5'],
    avg_cost_per_person: 500,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res11',
    name: 'Amma Mess',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.5,
    cuisine: 'south_indian',
    suitable_for: ['family', 'friends'],
    location: 'KK Nagar',
    src: '',
    description: 'Authentic Tamil Nadu meals',
    specialties: ['Meals', 'Biriyani', 'Parotta'],
    timings: '11:00 AM - 10:00 PM',
    nearby_hotels: ['hotel9', 'hotel10'],
    avg_cost_per_person: 200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res12',
    name: 'Konar Mess',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.4,
    cuisine: 'south_indian',
    suitable_for: ['family', 'friends'],
    location: 'East Masi Street',
    src: '',
    description: 'Famous for mutton dishes',
    specialties: ['Mutton Biriyani', 'Mutton Chukka'],
    timings: '11:00 AM - 10:00 PM',
    nearby_hotels: ['hotel7', 'hotel11'],
    avg_cost_per_person: 300,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res13',
    name: 'Surya Restaurant',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.3,
    cuisine: 'north_indian',
    suitable_for: ['family', 'friends'],
    location: 'KK Nagar',
    src: '',
    description: 'North Indian cuisine',
    specialties: ['Butter Chicken', 'Naan', 'Biryani'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel9', 'hotel10'],
    avg_cost_per_person: 400,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'res14',
    name: 'Fusion 9',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.5,
    cuisine: 'continental',
    suitable_for: ['couple', 'friends'],
    location: 'Race Course',
    src: '',
    description: 'Fusion cuisine restaurant',
    specialties: ['Pasta', 'Pizza', 'Burgers'],
    timings: '12:00 PM - 11:00 PM',
    nearby_hotels: ['hotel8', 'hotel10'],
    avg_cost_per_person: 600,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant16',
    name: 'Sree Annapoorna',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.5,
    cuisine: 'south_indian',
    suitable_for: ['family', 'solo'],
    location: 'Gandhipuram',
    src: COMMON_IMAGES.restaurant,
    description: 'Famous for South Indian breakfast',
    specialties: ['Idli', 'Dosa', 'Pongal'],
    timings: '6:00 AM - 10:00 PM',
    nearby_hotels: ['hotel16', 'hotel17'],
    avg_cost_per_person: 200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant17',
    name: 'Hari Bhavanam',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.4,
    cuisine: 'indian',
    suitable_for: ['family', 'solo'],
    location: 'RS Puram',
    src: COMMON_IMAGES.restaurant,
    description: 'Authentic Indian cuisine',
    specialties: ['Biryani', 'Non-vegetarian Dishes'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel18', 'hotel19'],
    avg_cost_per_person: 300,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant18',
    name: 'Annalakshmi Restaurant',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.3,
    cuisine: 'south_indian',
    suitable_for: ['family', 'solo'],
    location: 'Race Course',
    src: COMMON_IMAGES.restaurant,
    description: 'Traditional Tamil Cuisine',
    specialties: ['Traditional Tamil Cuisine'],
    timings: '11:00 AM - 10:00 PM',
    nearby_hotels: ['hotel20', 'hotel15'],
    avg_cost_per_person: 250,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant19',
    name: 'Junior Kuppanna',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.6,
    cuisine: 'south_indian',
    suitable_for: ['family', 'solo'],
    location: 'Gandhipuram',
    src: COMMON_IMAGES.restaurant,
    description: 'Kongu Nadu Cuisine',
    specialties: ['Kongu Nadu Cuisine'],
    timings: '11:00 AM - 11:00 PM',
    nearby_hotels: ['hotel16', 'hotel17'],
    avg_cost_per_person: 350,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant20',
    name: 'Shree Anandhaas',
    city: 'Coimbatore',
    city_id: 'coimbatore',
    rating: 4.2,
    cuisine: 'south_indian',
    suitable_for: ['family', 'solo'],
    location: 'RS Puram',
    src: COMMON_IMAGES.restaurant,
    description: 'Quick Bites and Traditional Meals',
    specialties: ['Quick Bites', 'Traditional Meals'],
    timings: '7:00 AM - 10:00 PM',
    nearby_hotels: ['hotel18', 'hotel19'],
    avg_cost_per_person: 200,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  },
  {
    id: 'restaurant6',
    name: 'Sree Annapoorna',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.5,
    cuisine: 'South Indian',
    suitable_for: ['family', 'solo'],
    location: 'Near Meenakshi Temple',
    src: COMMON_IMAGES.restaurant,
    description: 'Famous for South Indian breakfast',
    specialties: ['Idli', 'Dosa', 'Pongal'],
    timings: '6:00 AM - 10:00 PM',
    nearby_hotels: ['hotel9', 'hotel10'],
    avg_cost_per_person: 150,
    solo_friendly: true,
    family_friendly: true,
    couple_friendly: true
  }
];

export const activities: Activity[] = [
  {
    id: 'activity1',
    name: 'Marina Beach',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.5,
    location: 'Marina Beach Road',
    src: COMMON_IMAGES.activity,
    description: 'Longest urban beach in India',
    duration: '2-3 hours',
    best_time_to_visit: 'Evening',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel1', 'hotel2'],
    type: 'beach'
  },
  {
    id: 'activity2',
    name: 'Kapaleeshwarar Temple',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.6,
    location: 'Mylapore',
    src: COMMON_IMAGES.activity,
    description: 'Ancient Shiva temple',
    duration: '1-2 hours',
    best_time_to_visit: 'Morning',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel1', 'hotel2'],
    type: 'temple'
  },
  {
    id: 'activity3',
    name: 'VGP Universal Kingdom',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.3,
    location: 'ECR',
    src: COMMON_IMAGES.activity,
    description: 'Amusement park with rides',
    duration: '4-5 hours',
    best_time_to_visit: 'Daytime',
    price_per_person: 1000,
    suitable_for: ['family'],
    nearby_hotels: ['hotel1', 'hotel2'],
    type: 'amusement'
  },
  {
    id: 'activity4',
    name: 'Vivekananda House',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.2,
    location: 'Marina Beach',
    src: COMMON_IMAGES.activity,
    description: 'Historic house museum',
    duration: '1 hour',
    best_time_to_visit: 'Daytime',
    price_per_person: 50,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel1', 'hotel2'],
    type: 'museum'
  },
  {
    id: 'activity5',
    name: 'Phoenix MarketCity',
    city: 'Chennai',
    city_id: 'chennai',
    rating: 4.4,
    location: 'Velachery',
    src: COMMON_IMAGES.activity,
    description: 'Large shopping mall',
    duration: '3-4 hours',
    best_time_to_visit: 'Evening',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel1', 'hotel2'],
    type: 'shopping'
  },
  {
    id: 'activity6',
    name: 'Meenakshi Amman Temple',
    city: 'Madurai',
    city_id: 'city2',
    rating: 4.7,
    location: 'Madurai',
    src: COMMON_IMAGES.activity,
    description: 'Historic Hindu temple',
    duration: '2-3 hours',
    best_time_to_visit: 'Morning',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel3', 'hotel4'],
    type: 'temple'
  },
  {
    id: 'activity7',
    name: 'Thirumalai Nayak Palace',
    city: 'Madurai',
    city_id: 'city2',
    rating: 4.4,
    location: 'Madurai',
    src: COMMON_IMAGES.activity,
    description: '17th-century palace',
    duration: '1-2 hours',
    best_time_to_visit: 'Daytime',
    price_per_person: 100,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel3', 'hotel4'],
    type: 'palace'
  },
  {
    id: 'activity8',
    name: 'Gandhi Museum',
    city: 'Madurai',
    city_id: 'city2',
    rating: 4.2,
    location: 'Madurai',
    src: COMMON_IMAGES.activity,
    description: 'Gandhi memorabilia museum',
    duration: '1 hour',
    best_time_to_visit: 'Daytime',
    price_per_person: 20,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel3', 'hotel4'],
    type: 'museum'
  },
  {
    id: 'activity9',
    name: 'VOC Park and Zoo',
    city: 'Coimbatore',
    city_id: 'city3',
    rating: 4.4,
    location: 'Coimbatore',
    src: COMMON_IMAGES.activity,
    description: 'Zoo and amusement park',
    duration: '3-4 hours',
    best_time_to_visit: 'Daytime',
    price_per_person: 50,
    suitable_for: ['family'],
    nearby_hotels: ['hotel5', 'hotel6'],
    type: 'zoo'
  },
  {
    id: 'activity10',
    name: 'Brookefields Mall',
    city: 'Coimbatore',
    city_id: 'city3',
    rating: 4.5,
    location: 'Coimbatore',
    src: COMMON_IMAGES.activity,
    description: 'Shopping and entertainment',
    duration: '3-4 hours',
    best_time_to_visit: 'Evening',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel5', 'hotel6'],
    type: 'shopping'
  },
  {
    id: 'activity11',
    name: 'Gedee Car Museum',
    city: 'Coimbatore',
    city_id: 'city3',
    rating: 4.3,
    location: 'Coimbatore',
    src: COMMON_IMAGES.activity,
    description: 'Vintage car collection',
    duration: '1-2 hours',
    best_time_to_visit: 'Daytime',
    price_per_person: 100,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel5', 'hotel6'],
    type: 'museum'
  },
  {
    id: 'activity12',
    name: 'Gass Forest Museum',
    city: 'Coimbatore',
    city_id: 'city3',
    rating: 4.2,
    location: 'Coimbatore',
    src: COMMON_IMAGES.activity,
    description: 'Natural history museum',
    duration: '1-2 hours',
    best_time_to_visit: 'Daytime',
    price_per_person: 30,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel5', 'hotel6'],
    type: 'museum'
  },
  {
    id: 'activity13',
    name: 'Perur Pateeswarar Temple',
    city: 'Coimbatore',
    city_id: 'city3',
    rating: 4.6,
    location: 'Coimbatore',
    src: COMMON_IMAGES.activity,
    description: 'Ancient Shiva temple',
    duration: '1-2 hours',
    best_time_to_visit: 'Morning',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel5', 'hotel6'],
    type: 'temple'
  },
  {
    id: 'act6',
    name: 'Marudamalai Temple',
    city: 'Madurai',
    city_id: 'madurai',
    rating: 4.4,
    location: 'Marudamalai',
    src: COMMON_IMAGES.activity,
    description: 'Ancient temple dedicated to Lord Murugan',
    duration: '2-3 hours',
    best_time_to_visit: 'Morning',
    price_per_person: 0,
    suitable_for: ['solo', 'family', 'couple'],
    nearby_hotels: ['hotel3', 'hotel4'],
    type: 'temple'
  }
];

export const cities = [
  {
    id: 'chennai',
    name: 'Chennai',
    name_ta: 'சென்னை',
    description: 'Capital city of Tamil Nadu',
    description_ta: 'தமிழ்நாட்டின் தலைநகரம்'
  },
  {
    id: 'kanchipuram',
    name: 'Kanchipuram',
    name_ta: 'காஞ்சிபுரம்',
    description: 'City of Thousand Temples',
    description_ta: 'ஆயிரம் கோயில்களின் நகரம்'
  },
  {
    id: 'kodaikanal',
    name: 'Kodaikanal',
    name_ta: 'கோடைக்கானல்',
    description: 'Princess of Hill Stations',
    description_ta: 'மலை வாசஸ்தலங்களின் இளவரசி'
  }
]; 