import React from 'react';

interface CityDescriptionProps {
  city: string;
}

const cityDescriptions: { [key: string]: string } = {
  'Chennai': '🏙️ Chennai, the capital of Tamil Nadu, is one of India\'s largest cultural, economic, and educational hubs. A city that seamlessly blends modernity with tradition, Chennai is known for its beautiful beaches, rich history, and vibrant culture. It\'s home to ancient temples, colonial-era landmarks, and bustling markets. The city is also famous for its classical music and dance forms, especially Bharatanatyam.\n\nKey Attractions:\n• Marina Beach: One of the longest urban beaches in the world\n• Kapaleeshwarar Temple: A historic temple dedicated to Lord Shiva\n• Fort St. George: A symbol of British colonial rule\n• Chennai Museum: One of the oldest museums in India\n\nCulture:\nChennai is the hub of South Indian classical music and dance. The city\'s cultural calendar is filled with the famous December Music Season, drawing artists and enthusiasts from around the globe. The city is also known for its delicious Tamil cuisine, including idli, dosa, sambar, and chettinad dishes.',
  
  'Madurai': '🌆 Madurai, one of the oldest cities in India, is located in Tamil Nadu and is famous for its magnificent temples and rich cultural heritage. Known as the "Athens of the East," Madurai\'s iconic Meenakshi Amman Temple is a marvel of Dravidian architecture. The city is a major center for Tamil culture, known for its festivals, music, and traditional arts.\n\nKey Attractions:\n• Meenakshi Amman Temple: A grand temple with towering gopurams\n• Thirumalai Nayakkar Palace: A beautiful blend of Islamic and Dravidian architecture\n• Gandhi Memorial Museum: Dedicated to Mahatma Gandhi\'s legacy\n\nCulture:\nMadurai has a unique vibe with bustling markets, aromatic street foods, and an ever-present sense of spirituality. Traditional arts like Kolam (floor art) and Carnatic music are deeply rooted in the city.',
  
  'Kanyakumari': '🌅 Kanyakumari, the southernmost tip of India, is where the Arabian Sea, Bay of Bengal, and Indian Ocean meet. Known for its breathtaking sunrise and sunset views, Kanyakumari is a sacred pilgrimage site, featuring the Vivekananda Rock Memorial and Thiruvalluvar Statue.\n\nKey Attractions:\n• Vivekananda Rock Memorial: A symbol of spiritual unity\n• Thiruvalluvar Statue: A towering statue of the Tamil poet-saint\n• Kanyakumari Temple: A famous temple dedicated to the goddess\n\nCulture:\nThe city has a unique blend of spiritual significance and natural beauty. The Kanyakumari Temple and local festivals add a sense of spirituality, while its proximity to various water bodies makes it ideal for photography and sightseeing.',
  
  'Ooty': '🌲 Ooty, the "Queen of Hill Stations," is nestled in the Nilgiri hills of Tamil Nadu. Known for its picturesque landscapes, tea gardens, and pleasant climate, Ooty is a popular getaway for nature lovers and adventure seekers. The city offers a charming colonial touch with British-era buildings.\n\nKey Attractions:\n• Ooty Lake: Perfect for boating with scenic views\n• Botanical Gardens: A lush green haven with thousands of plant species\n• Nilgiri Mountain Railway: A UNESCO World Heritage Site\n\nCulture:\nOoty\'s British influence is visible in its architecture and lifestyle, and the local Toda tribe adds a unique cultural experience. The hill station\'s famous tea gardens offer a glimpse into the tea cultivation process.',
  
  'Kodaikanal': '🌄 Kodaikanal, another serene hill station in Tamil Nadu, is famous for its misty mountains, crystal-clear lakes, and dense forests. Often referred to as the "Princess of Hill Stations," Kodaikanal offers a peaceful retreat with natural beauty, rich flora, and fauna.\n\nKey Attractions:\n• Kodaikanal Lake: A star-shaped lake surrounded by lush forests\n• Coaker\'s Walk: A scenic path offering panoramic views\n• Pillar Rocks: Giant rock formations providing breathtaking views\n\nCulture:\nKodaikanal is known for its scenic beauty and relaxed atmosphere. The town is famous for home-made chocolates and a variety of locally grown fruits and flowers.',
  
  'Thanjavur': '🏛️ Thanjavur, known for its grand temples and vibrant culture, is a city steeped in history. It was once the capital of the Chola Empire, and the Brihadeeswarar Temple, a UNESCO World Heritage site, stands as a symbol of the city\'s architectural brilliance.\n\nKey Attractions:\n• Brihadeeswarar Temple: A monumental temple dedicated to Lord Shiva\n• Thanjavur Maratha Palace: A historical palace with museums\n• Tanjore Art Gallery: A museum displaying ancient sculptures\n\nCulture:\nThanjavur is a major center for Carnatic music, and the Tanjore painting style is recognized worldwide. The city also offers authentic Chettinad cuisine.',
  
  'Kanchipuram': '🛕 Kanchipuram, known as the "City of Thousand Temples," is one of India\'s seven Moksha-puris (sacred cities). It has a rich spiritual and cultural heritage, with ancient temples, stunning architecture, and vibrant handloom silk industry.\n\nKey Attractions:\n• Kailasanathar Temple: One of the oldest temples\n• Varadharaja Perumal Temple: An ancient Vishnu temple\n• Kanchipuram Silk Weaving Industry: Known for exquisite silk sarees\n\nCulture:\nKanchipuram is famous for its silk sarees, which are a major cultural export. It is also a center of Vedanta philosophy and is closely linked to the spiritual teachings of Adi Shankaracharya.',
  
  'Coimbatore': '🏭 Coimbatore, known as the "Manchester of South India," is a major industrial city in Tamil Nadu. It is also famous for its educational institutions, beautiful temples, and proximity to hill stations like Ooty.\n\nKey Attractions:\n• Marudhamalai Temple: A serene hilltop temple\n• VOC Park: A peaceful park with a zoo\n• Perur Pateeswarar Temple: A famous historic temple\n\nCulture:\nCoimbatore is known for its textile industry and is a major center for engineering goods manufacturing. It is also famous for its hospitality and local cuisine, including Kongu cuisine.',
  
  'Rameshwaram': '🛕 Rameshwaram, a holy town located on Pamban Island, is one of the four Char Dham pilgrimage sites. Known for its temple and beach, it attracts religious tourists and nature lovers alike.\n\nKey Attractions:\n• Ramanathaswamy Temple: A significant temple dedicated to Lord Shiva\n• Pamban Bridge: A historical sea bridge\n• Dhanushkodi: A ghost town with scenic beauty\n\nCulture:\nRameshwaram is an important pilgrimage site, particularly for Hindus. The town is also famous for its beautiful beaches, and the local seafood cuisine is highly rated.',
  
  'Yelagiri': '🌄 Yelagiri is a serene hill station in Tamil Nadu, perfect for nature enthusiasts and adventure seekers. With its scenic valleys, forests, and pleasant weather, Yelagiri is ideal for trekking, paragliding, and relaxing by the lakes.\n\nKey Attractions:\n• Yelagiri Lake: A scenic lake for boating\n• Swamimalai Hill: A trekking destination\n• Jalagamparai Waterfalls: A beautiful waterfall\n\nCulture:\nYelagiri is a peaceful getaway offering a blend of natural beauty and adventure. It is less commercialized than other hill stations, making it an excellent location for a quiet retreat.'
};

export const CityDescription: React.FC<CityDescriptionProps> = ({ city }) => {
  const description = cityDescriptions[city] || '🛕 Rameshwaram, a holy town located on Pamban Island, is one of the four Char Dham pilgrimage sites. Known for its temple and beach, it attracts religious tourists and nature lovers alike.\n\nKey Attractions:\n• Ramanathaswamy Temple: A significant temple dedicated to Lord Shiva\n• Pamban Bridge: A historical sea bridge\n• Dhanushkodi: A ghost town with scenic beauty\n\nCulture:\nRameshwaram is an important pilgrimage site, particularly for Hindus. The town is also famous for its beautiful beaches, and the local seafood cuisine is highly rated.';

  return (
    <div className="bg-white rounded-lg shadow-md p-6 mb-8">
      <h2 className="text-2xl font-semibold text-gray-800 mb-4">About {city}</h2>
      <div className="text-gray-600 leading-relaxed whitespace-pre-line">{description}</div>
    </div>
  );
}; 